### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by olivif** [olivif/blurry-blog#1]
- [x] fix social icons
- [x] fix social links layout
- [x] add divider
- [x] add blog button 
- [x] make blog button slide in
- [x] fix readability on blog post list
